pipeline {
    agent any

    tools {
        jdk 'jdk-21'
        maven 'maven-3'
        python 'python-3.10'
    }

    environment {
        FLASK_IMAGE = "bookstore-flask"
        JAVA_IMAGE  = "bookstore-java"
    }

    stages {

        stage('Build Flask Server') {
            steps {
                dir('Week_1/Day_3_and_4/flask_server') {
                    bat 'python -m venv venv'
                    bat 'venv\\Scripts\\pip install -r requirements.txt'
                }
            }
        }

        stage('Build Java Server') {
            steps {
                dir('Week_1/Day_3_and_4/java_server') {
                    bat 'mvn clean package'
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                bat 'docker build -t %FLASK_IMAGE% Week_1/Day_3_and_4/flask_server'
                bat 'docker build -t %JAVA_IMAGE% Week_1/Day_3_and_4/java_server'
            }
        }

        stage('Run Containers') {
            steps {
                bat 'docker rm -f flask_container || exit 0'
                bat 'docker rm -f java_container || exit 0'

                bat 'docker run -d -p 5000:8080 --name flask_container %FLASK_IMAGE%'
                bat 'docker run -d -p 8081:8080 --name java_container %JAVA_IMAGE%'
            }
        }
    }

    post {
        success {
            echo 'Pipeline executed successfully'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}